kind = "api"
previewPath = "/"
title = "Bingo Mini App"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "Bingo App"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace && python main.py"
